rayuela/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Rayuela API",
      default_version='v1',
      description="Documentación de la API de Rayuela",
   ),
   public=False,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('rayuelaApp.urls')),
    #path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

rayuelaApp/urls.py
from rayuelaApp.views import user, admin, project, game_elements, checkin ,badge , challenge , assignment, time_restriction
from rayuelaApp.views.game_element_view import GameElementView
from django.urls import path, include

urlpatterns = [
    path('', user.index,name='index'),
    path('home/',user.home, name='home'),  
    path('logout/',user.logout, name='logout'),
    path('register/',user.register,name='register'),
    path('register_user/',user.register_user,name='register_user'),
    path('login/',user.login, name='login'), 
    path('verificate/',user.verificate, name='verificate'),
    path('activate_account/',user.activate_account,name='activate_account'),
    path('active_account/',user.active_account,name='active_account'),
    path('create_admin/',admin.create_admin,name='create_admin'),
    path('modify_project/',project.modify_project,name='modify_project'),
    path('modify/',game_elements.modify,name='modify'),
    path('register_admin/',admin.register_admin,name='register_admin'),
    path('create_project/',project.create_project,name='create_project'),
    path('register_project/',project.register_project,name='register_project'),
    path('edit_project/',project.edit_project,name='register_project'),
    path('create_badge/',badge.badge,name='create_badge'),
    path('process_badge/',badge.process_badge,name='process_badge'),
    path('change_state/',game_elements.change_state,name='change_state'),
    path('create_challenge/',challenge.challenge,name='create_challenge'),
    path('process_challenge/',challenge.process_challenge,name='process_challenge'),
    path('game_element_view/',GameElementView.as_view(),name='game_element_view'),
    path('create_checkin/',checkin.checkin,name='create_checkin'),
    path('process_checkin/',checkin.process_checkin,name='process_checkin'),
    path('view_game_elements/',game_elements.view_game_elements, name='view_game_elements'),
    path('asign_challenge/',challenge.asign_challenge,name="asign_challenge"),
    path('asign_badge/',badge.asign_badge,name="asign_badge"),
    path('see_my_game_elements/',user.see_my_game_elements,name='see_my_game_elements'),
    path('edit_profile/',user.edit_profile,name='edit_profile'),
    path('process_edit_profile/',user.process_edit_profile,name='process_edit_profile'),
    path('game_elements_project/',project.game_elements_project,name='game_elements_project'),
    path('modify_challenge/',challenge.modify_challenge, name='modify_challenge'),
    path('modify_badge/',badge.modify_badge, name='modify_badge'),
    path('see_all_projects/',project.see_all_projects,name='see_all_projects'),
    path('asign_project/',project.asign_project,name='asign_project'),
    path('my_projects/',user.my_projects,name='my_projects'),
    path('add_like_dislike/',assignment.add_like_dislike,name='add_like_dislike'),
    path('create_scorings/',assignment.create_scorings,name='create_scorings'),
    path('create_time_restriction/',time_restriction.time_restriction,name='create_time_restriction'),
    path('process_time_restriction/',time_restriction.process_time_restriction,name='process_time_restriction'),
    path('modify_project_root/',project.modify_project_root,name='modify_project_root'),
    path('process_modify_project/',project.process_modify_project,name='process_modify_project'),
    path('disjoin_project/',project.disjoin_project,name='disjoin_project'),
    path('api/', include('rayuelaApp.api.routers'), name='api'),
]

rayuelaApp/models/check_in.py
from django.db import models
from rayuelaApp.models.project import Project
from rayuelaApp.models.user  import User
from datetime import datetime


class CheckIn(models.Model):

    user=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    project=models.ForeignKey(Project,on_delete=models.DO_NOTHING)
    latitude=models.CharField(blank=False,null=False,max_length=500)
    longitude=models.CharField(blank=False,null=False,max_length=500)
    datetime=models.DateTimeField(null=False, blank=False)
    

    class Meta:
        verbose_name='CheckIn'
        verbose_name_plural="CheckIns"
        db_table='check_in'

    def __str__(self):
        return f'{self.user},{self.project},{self.latitude},{self.longitude},{self.datetime}'


    def get_date(self):       
        return self.datetime
    
    def get_latitude(self):
        return self.latitude
    
    def get_longitude(self):
        return self.longitude

rayuelaApp/models/game_element.py
from django.db import models
from model_utils.managers import InheritanceManager
from rayuelaApp.models.user  import User
from rayuelaApp.models.project_subarea import ProjectSubArea
from rayuelaApp.models.project import Project
from rayuelaApp.models.time_restriction import TimeRestriction


class GameElement(models.Model):
    objects = InheritanceManager() 
    name=models.CharField(blank=False,unique=True,null=False,max_length=150)
    owner=models.ForeignKey(User,null=True,blank=True,on_delete=models.DO_NOTHING)
    goal=models.IntegerField(blank=True,null=True)
    rate=models.FloatField(blank=True,null=True)
    project=models.ForeignKey(Project,blank=False,null=False,on_delete=models.DO_NOTHING,related_name='%(class)s')
    area=models.ForeignKey(ProjectSubArea,null=True,blank=True,on_delete=models.DO_NOTHING)
    time_restriction=models.ForeignKey(TimeRestriction,null=True,blank=True,on_delete=models.DO_NOTHING)
    checkin=models.ManyToManyField('rayuelaApp.checkin', related_name='%(class)s_checkins')
    user_actives=models.ManyToManyField('rayuelaApp.user', related_name='%(class)s_actives')
    public=models.BooleanField(blank=False,null=False,default=1)

    class Meta:
        verbose_name='GameElement'
        verbose_name_plural="GameElements"
        db_table='game_element'


    def __str__(self):
        return f'{self.name},{self.goal},{self.owner},{self.rate},{self.project}'     

    def is_valid_checkin(self,checkin_,user_id):
        return (self.is_my_user_active(user_id) and self.time_restriction.is_valid_time(checkin_.get_date()) and self.area.is_valid_area(checkin_.get_latitude(),checkin_.get_longitude()) and self.public and self.get_progress_user(user_id) < 100.0)
     
    def get_progress_user(self,user_id_):
        assignment_ge=self.get_assignment_set().get(user_id=user_id_)     
        return assignment_ge.get_progress()
             
    def is_valued(self,user_id_):      
        if self.get_assignment_set().get(user_id=user_id_).get_like_dislike() is None:
            return False
        return True

    def get_assignment_id(self,user_id_):
        return self.get_assignment_set().get(user_id=user_id_).get_id()

    def is_my_user_active(self,user_id):
         return (self.user_actives.filter(id=user_id).exists())
                 
    def get_id_project(self):
        return self.project.get_id()

    def get_name(self):
        return self.name

    def get_id(self):
        return self.id

    def get_goal(self):
        return self.goal
    
    def get_checkins(self):
        return self.checkin

    def get_project(self):
        return self.project

    def add_area(self,area):
        self.area=area
        self.save()

    def get_area(self):
        return self.area

    def change_state(self):
        self.public = (not self.public)
        self.save()

    def get_assignment_set(self):
        return self.assignment_set

    def increment_progress(self,user_id_):        
        progress=self.get_assignment_set().get(user_id=user_id_)
        progress.increment_progress(self.get_goal(),self.get_checkins().filter(user_id=user_id_).count())

    
    def update(self,name,area,time_restriction,goal):
       self.name=name
       self.area=area
       self.time_restriction=time_restriction
       self.goal=goal
       self.save()
       
    def scoried(self,user_id):
        if self.get_assignment_set().get(user_id=user_id).scoring_set.count() == 0:
            return False
        return True


    def get_state(self):
        if self.public:
            return 'Restaurado'
        return 'Borrado'
    
    def add_time_restriction(self,time_restriction):
        self.time_restriction=time_restriction

    def get_time_restriction(self):
        return self.time_restriction

    def add_player(self,player):
        self.user_actives.add(player)
        self.save()

    def add_checkin(self,checkin):
        self.checkin.add(checkin)

rayuelaApp/forms.py
from django import forms
from rayuelaApp.models.project  import Project
from rayuelaApp.models.badge import  Badge
from rayuelaApp.models.user import User


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["image"]
        
    def procces(self,path_image):
        if self.is_valid():    
            self.save()

class BadgeForm(forms.ModelForm):
    class Meta:
        model = Badge
        fields = ["image"]

    def procces(self,path_image):
        if self.is_valid():    
            self.save()

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['profile_image']

    def procces(self,path_image):
        if self.is_valid():    
            self.save()

rayuelaApp/views/admin.py
from django.shortcuts import redirect, render
from rayuelaApp.models.user import User
from rayuelaApp.models.role import Role
from rayuelaApp.utils.System import System
from django.contrib import messages
from werkzeug.security import generate_password_hash


def register_admin(request):
  
    if User.objects.filter(email__exact=request.POST['email']).exists() or  User.objects.filter(username__exact=request.POST['username']).exists():
        messages.error(request,'Nombre de usuario/email ya registrado')
        return redirect('create_admin')
    if not request.POST['email'] or not request.POST['username'] or not request.POST['password'] or not request.POST['repeat_password'] or not request.POST['name'] or (request.POST['password'] != request.POST['repeat_password']):
        if (request.POST['password'] != request.POST['repeat_password']):
            messages.error(request,'Las contraseñas no coinciden')
        else:
            messages.error(request,'Todos los campos deben estar completos')
        return redirect('create_admin')
        
    user=User(email=request.POST['email'],username=request.POST['username'],complete_name=request.POST['name'],role_id=Role.objects.get(name='ADMIN'),password=generate_password_hash(request.POST['password'], 'sha256', 10))
    user.save()
    messages.success(request,'¡Administrador dado de alta con éxito')
    return redirect('create_admin')


def create_admin(request):
     if System.is_logged(request):
          if System.is_root(request):
            return render (request,'rayuelaApp/create_admin.html',{'nav':'block','create_admin':System.get_navbar_color})
          return redirect('home')
     return redirect('index')  

rayuelaApp/views/assignment.py
from rayuelaApp.utils.System import System
from rayuelaApp.models.assignment import Assignment
from django.shortcuts import redirect
from django.contrib import messages




def add_like_dislike(request):
    if System.is_logged(request):
        if System.is_player(request):   
            Assignment.objects.get(id=request.POST['assignment_id']).add_like_dislike(request.POST['assignment_bool'])
            messages.success(request,'¡Su valoración se ha guardado correctamente!')
            return redirect('see_my_game_elements')           
        return redirect('home')
    return redirect('index')

def create_scorings(request):
    if System.is_logged(request):
        if System.is_player(request): 
            Assignment.objects.get(id=request.POST['id']).add_scorings(request.POST)              
            messages.success(request,'¡Su opinión se ha guardado correctamente!')
            return redirect('see_my_game_elements')
        return redirect('home')
    return redirect('index')

rayuelaApp/views/badge.py
from django.shortcuts import redirect, render
from rayuelaApp.models.user import  User
from rayuelaApp.models.project import Project
from rayuelaApp.models.project_subarea import ProjectSubArea
from rayuelaApp.models.time_restriction import TimeRestriction
from rayuelaApp.views import game_elements
from rayuelaApp.utils.System import System
from rayuelaApp.models.badge import Badge
from rayuelaApp.models.assignment import Assignment
from django.contrib import messages
from rayuelaApp.forms import BadgeForm





def badge(request):
    if System.is_logged(request):
          if System.is_admin(request):
              return render(request, 'rayuelaApp/game_elements/create_badge.html',{'nav':'block','create_badge':System.get_navbar_color,'badges':Badge.objects.all(),'projects':Project.objects.filter(admins=request.session['id'])})
          return redirect('home')  
    return redirect('index') 

def process_badge(request):
    if System.is_logged(request):
          if System.is_admin(request):
              if not request.POST['name'] or not request.POST['area'] or not request.POST['project'] or not request.POST['time_restriction'] or not request.POST['goal']:
                  messages.error(request,'Debe ingresar todos los campos') 
                  return badge(request)               
              elif Badge.objects.filter(name__iexact=request.POST['name'],project=Project.objects.get(id__exact=request.POST['project'])).exists():
                  messages.error(request,'Ya hay una insignia con ese nombre') 
                  return badge(request)   
              badge_= Badge(name=request.POST['name'],area=ProjectSubArea.objects.get(id__exact=request.POST['area']),time_restriction=TimeRestriction.objects.get(id__exact=request.POST['time_restriction']),goal=request.POST['goal'],owner=User.objects.get(id__exact=request.session['id']),project=Project.objects.get(id__exact=request.POST['project']))                
              badge_.add_parent(int(request.POST['select']))    
              badge_.save()            
              form = BadgeForm(data=request.POST, files=request.FILES, instance=badge_)
              form.procces(badge_.get_path_image())
              messages.success(request,'Se ha creado correctamente')
              return badge(request)   
          return redirect('home')  
    return redirect('index') 

def asign_badge(request):
    if System.is_logged(request):
          if System.is_player(request):
            badge= Badge.objects.get(id=request.POST['badge_id'])
            user = User.objects.get(id=request.session['id'])
            user.add_gamelement_active(badge)
            bp = Assignment(user=user,game_element=badge)
            bp.save()
            messages.success(request,'Insignia %s  asignado con éxito'  % (badge.get_name()))
            request.session['old']=badge.get_id_project()
            return redirect ('view_game_elements')
          return redirect('home')  
    return redirect('index')  

def modify_badge(request):
    if System.is_logged(request):
          if System.is_admin(request):  
                try:
                    request.POST['name']
                except:
                    return redirect ('home')
                if not request.POST['name'] or not request.POST['area'] or  not request.POST['time_restriction'] or not request.POST['goal']:
                    messages.error(request,'Debe ingresar todos los campos')
                    return game_elements.modify(request,True)               
                elif Badge.objects.filter(name__iexact=request.POST['name'],project=Project.objects.get(id__exact=request.POST['id_project'])).exclude(id__exact=request.POST['id']).exists():
                    messages.error(request,'Ya hay una insignia con ese nombre')
                    return game_elements.modify(request,True)       
                else: 
                    badge_=Badge.objects.get(id__exact=request.POST['id'])
                    badge_.update(request.POST['name'],ProjectSubArea.objects.get(id__exact=request.POST['area']),TimeRestriction.objects.get(id__exact=request.POST['time_restriction']),request.POST['goal'],int(request.POST['select']))             
                    form = BadgeForm(data=request.POST, files=request.FILES, instance=badge_)
                    form.procces(badge_.get_path_image())
                    messages.success(request,'Insignia modificada correctamente')
                return game_elements.modify(request,True)     
          return redirect('home')  
    return redirect('index')  

rayuelaApp/templates/rayuelaApp/game_elements/create_badge.html
{% extends 'rayuelaApp/base/base.html' %}
{% load static %}
{% block title %}
  Nuevo Desafío
{% endblock %}

{% block link %}   <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
crossorigin=""/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css"/> {% endblock %}

{% block content %}
  <div class="col-md-6 mb-5 mt-0">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Crear Insignia</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form action="/process_badge/" id="send" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
          <div class="col-12 col-md-12">
            <label class="invalid-feedback d-block">
              {% for message in messages %}
                {% if message.tags == 'error' %}
                  *{{ message }}
                {% endif %}
              {% endfor %}
            </label>
            <div class="form-group">
              <label for="exampleInputEmail1">Nombre</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Ingresar nombre del desafío" required>
            </div>
            <div class="form-group">
              <label>Asignar al proyecto</label>
             
              <select id="id_project" name="project" class="form-control select2 select2-info" data-dropdown-css-class="select2-info" data-placeholder="Seleccionar proyecto" style="width: 100%;" required>          
                <option value='#'>--------</option>
                {% for project in projects %}
                <option  value='{{ project.id }}'>{{ project.name }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group">
              <label>Asignar área</label>
              <select id="id_area" name="area" class="form-control select2 select2-info" data-dropdown-css-class="select2-info" data-placeholder="Seleccionar áreas" style="width: 100%;" required>          
                
              </select><br>
              <div id="map" ></div>
            </div>
           
            <div class="form-group">
              <label>Asignar restricción de tiempo</label>
              <select id="id_time_restriction" name="time_restriction" class="form-control select2 select2-info" data-dropdown-css-class="select2-info" data-placeholder="Seleccionar restricción de tiempo" style="width: 100%;" required>                       
              </select>
            </div>
            <div class="form-group">
                <label>Insignia Requerida</label>
                <select id="" name="select" class="form-control select2 select2-info" data-dropdown-css-class="select2-info"  data-placeholder="Seleccionar administradores" style="width: 100%;" required>          
                  <option value='0'>Ninguna</option>
                  {% for badge in badges %}
                  <option value='{{ badge.id }}'>{{ badge.name }}</option>
                  {% endfor %}
                </select>
              </div>
           
            <div class="form-group">
              <label for="exampleFormControlFile1">Imagen de la insignia</label>
              <input type="file" class="form-control-file" accept="image/*" name="image" />
            </div>
            <!--<div class="form-group">
              <label for="exampleInputEmail1">Seleccionar área</label>
              <div id="map" style="height: 180px !important"></div>
            </div>-->
            
            <div class="form-group">
              <label for="exampleInputEmail1">Meta de check-ins</label>
              <input type="number" class="form-control" id="goal" name="goal" placeholder="Meta de check ins" required>
            </div>
            

          </div>
        </div>
        <!-- /.card-body -->
      </form>
      <div class="card-footer">
        <button onclick="$.confirmation(send);"  class="btn btn-primary">Crear Insignia</button>
      </div>
    </div>
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <div class="col-md-12 mb-1">
          <div class="row">
            <div class="col-12 d-flex justify-content-center">
              <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="icon fas fa-check"></i>
                {{ message }}
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

{% block scripts %}
<script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
     integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
     crossorigin=""></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
     
     <script src="{% static 'dist/js/subareas_map.js' %}"></script>
     <script src="{% static 'dist/js/get_tr_areas.js' %}"></script>
<script src="{% static 'dist/js/sweetalert2.all.min.js' %}"></script>
<script src="{% static 'dist/js/showconfirmation.js' %}"></script>
{% endblock %}

rayuelaApp/templates/rayuelaApp/game_elements/create_challenge.html
{% extends 'rayuelaApp/base/base.html' %}
{% load static %}
{% block title %}
  Nuevo Desafío
{% endblock %}

{% block link %}   <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
crossorigin=""/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css"/> {% endblock %}

{% block content %}
  <div class="col-md-6 mb-5 mt-0">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Crear Desafío</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form action="/process_challenge/" id="send" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
          <div class="col-12 col-md-12">
            <label class="invalid-feedback d-block">
              {% for message in messages %}
                {% if message.tags == 'error' %}
                  *{{ message }}
                {% endif %}
              {% endfor %}
            </label>
            <div class="form-group">
              <label for="exampleInputEmail1">Nombre</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Ingresar nombre del desafío" required>
            </div>
            <div class="form-group">
              <label>Asignar al proyecto</label>
             
              <select id="id_project" name="project" class="form-control select2 select2-info" data-dropdown-css-class="select2-info" data-placeholder="Seleccionar projecto" style="width: 100%;" required>          
                <option value='#'>--------</option>
                {% for project in projects %}
                <option  value='{{ project.id }}'>{{ project.name }}</option>
                {% endfor %}
              </select>
            </div>
            
           
            <div class="form-group">
              <label>Asignar restricción de tiempo</label>
              <select id="id_time_restriction" name="time_restriction" class="form-control select2 select2-info" data-dropdown-css-class="select2-info" data-placeholder="Seleccionar restricción de tiempo" style="width: 100%;" required>                       
              </select>
            </div>
            <div class="form-group">
              <label>Área</label>
              <select id="id_area" name="area" class="form-control select2 select2-info" data-dropdown-css-class="select2-info" data-placeholder="Seleccionar áreas" style="width: 100%;" required>          
                
              </select>
            
              <br>
              <div id="map" ></div>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Meta de check-ins</label>
              <input type="number" class="form-control" id="goal" name="goal" placeholder="Meta de check ins" required>
            </div>
            

          </div>
        </div>
        <!-- /.card-body -->
      </form>
      <div class="card-footer">
        <button onclick="$.confirmation(send);"  class="btn btn-primary">Crear Desafío</button>
      </div>
    </div>
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <div class="col-md-12 mb-1">
          <div class="row">
            <div class="col-12 d-flex justify-content-center">
              <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="icon fas fa-check"></i>
                {{ message }}
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

{% block scripts %}
<script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
     integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
     crossorigin=""></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
    
     <script src="{% static 'dist/js/subareas_map.js' %}"></script>
     <script src="{% static 'dist/js/get_tr_areas.js' %}"></script>
<script src="{% static 'dist/js/sweetalert2.all.min.js' %}"></script>
<script src="{% static 'dist/js/showconfirmation.js' %}"></script>
{% endblock %}

rayuelaApp/templates/rayuelaApp/game_elements/modify_challenge.html
{% extends 'rayuelaApp/base/base.html' %}
{% load static %}
{% block title %}
  Modificar Desafío
{% endblock %}
{% block link %}   <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
crossorigin=""/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css"/> {% endblock %}
{% block content %}
<div class="col-md-6"> 
    <div class="card card-primary">
        <div class="card-header">
        <h3 class="card-title">Modificar {{ challenge.name }}</h3>
        </div>
        
        
        <form action="/modify_challenge/" id="send" method="post" enctype="multipart/form-data"> {% csrf_token %}
        <div class="card-body">
        <div class="form-group ">
       
          <label class="invalid-feedback d-block">{% for message in messages %}{% if message.tags == 'error' %}*{{ message }}{% endif %}{% endfor %}</label>
            <label for="exampleInputEmail1">Nombre del desafío</label>
            <input type="text" class="form-control" name="name" placeholder="Ingrese un nombre" value='{{ challenge.name }}'>
            <input type='hidden' class="form-control" name='id' value="{{ challenge.id }}"></input>
            <input type='hidden' class="form-control" id='id_project' name='id_project' value="{{ challenge.project_id }}"></input>
        </div>
        
        <div class="form-group">                
          <label>Meta de check-ins</label>
          <input type="text" class="form-control" name="goal" placeholder="Ingrese una meta" value='{{ challenge.goal }}'>              
        </div>
               
          <div class="form-group">
            <label>Asignar área</label>
            <select id="id_area" name="area" class="form-control select2 select2-info" data-dropdown-css-class="select2-info" data-placeholder="Seleccionar áreas" style="width: 100%;" required>          
              
            </select><br>
            <div id="map" ></div>
          </div>
    
            <div class="form-group">
              <label>Asignar restricción de tiempo</label>
              <select id="" name="time_restriction" class="form-control select2 select2-info" data-dropdown-css-class="select2-info"  data-placeholder="Seleccionar restricción de tiempo" style="width: 100%;" >          
                {% for time_restriction in time_restrictions %}
                <option value='{{ time_restriction.id }}'>{{ time_restriction.name }}</option>
                {% endfor %}
              </select>
            </div>
          
        
       
          </form>
        </div>
     
        <div class="card-footer">
        <button onclick="$.confirmation(send);"  class="btn btn-primary">Guardar cambios</button>
        </div>
        
        </div>
     
        {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="col-md-12 mb-1">
          <div class="row">
            <div class="col-12 d-flex justify-content-center">
              <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="icon fas fa-check"></i> 
                {{ message }}
                </div>
          </div>
        </div>
        </div>
        {% endif %}
        {% endfor %}
    
  </div>
{% endblock %}
{% block scripts %}

<script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
     integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
     crossorigin=""></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
<script src="{% static 'dist/js/subareas_map.js' %}"></script>
<script src="{% static 'dist/js/get_tr_areas_.js' %}"></script>
<script src="{% static 'dist/js/sweetalert2.all.min.js' %}"></script>
    <script src="{% static '/dist/js/showconfirmation.js' %}"></script>
{% endblock %}